name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rustfmt
        working-directory: ./native
        run: cargo fmt --all --check
      - name: Clippy
        working-directory: ./native
        run: cargo clippy --all-targets --all-features -- -D warnings
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest, macos-14 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: gradle test
