name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v3
      - name: Rustfmt
        working-directory: ./native
        run: cargo fmt --all --check
      - name: Clippy
        working-directory: ./native
        run: cargo clippy --all-targets --all-features -- -D warnings
  test-native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo test --all-features
        working-directory: ./native
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest, macos-14 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v3
      - name: Test
        run: ./gradlew test
