name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-native:
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, macos-14 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew '-Pcargo.profile=release' :native:build
      - uses: actions/upload-artifact@v4
        with:
          name: native-${{ matrix.os }}
          path: native/build/libs
          retention-days: 1
          if-no-files-found: error
  build:
    runs-on: ubuntu-latest
    needs: build-native
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v3
      - uses: actions/download-artifact@v4
        with:
          pattern: native-*
          path: src/main/resources/native
          merge-multiple: true
      - run: ./gradlew '-Pkairs.skipNative=true' build publish
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          OCPD_SIGN_KEY: ${{ secrets.OCPD_SIGN_KEY }}
          OCPD_SIGN_KEY_ID: ${{ secrets.OCPD_SIGN_KEY_ID }}
          OCPD_SIGN_PASSPHRASE: ${{ secrets.OCPD_SIGN_PASSPHRASE }}
